### ISSUE TITLE
can we precompile the css?

### ISSUE THREAD

**Issue by luxzeitlos** [Romanior/ember-intl-phone-input#2]
is there a way to use this without using `ember-cli-less`?

**Comment by Romanior** [comment]
Not now, unfortunately, I will give it another push on the weekend or later this week. I need to add tests and support for SASS and plain scc.

**Comment by luxzeitlos** [comment]
awesome! For now I just dumped the compiled CSS from the dummy app. I just thought I would open an issue to track this

**Comment by Romanior** [comment]
A bit late, but `0.3.3` brings pre-compiled css and many other fixes
https://ember-twiddle.com/c38e181747aa387fb4cdfd4c9ad36315?openFiles=twiddle.json%2C
