### ISSUE TITLE
Flags and dropdown arrow not showing 

### ISSUE THREAD

**Issue by isAlmogK** [Romanior/ember-intl-phone-input#7]
For some reason you can't see the flags and dropdown or drop-down arrow attached screenshot 

<img width="606" alt="screen shot 2018-08-20 at 4 27 08 pm" src="https://user-images.githubusercontent.com/169507/44323650-20f86700-a496-11e8-96ac-d54781b44de1.png">

My code 

{{intl-phone-input value=driver.phone}}

which is wrapped in  <div class="ui form">

**Comment by Romanior** [comment]
Hello, very likely you are not using `ember-power-select` in you project, and thus its styles were not applied. Can you please import power select styles and let me know http://ember-power-select.com/docs/styles if it works.
Additionally, you can check how the dummy project uses styles for styling the form
`/ember-intl-phone-input/tests/dummy/app/styles/app.less`

Btw are you using LESS css-preprocessor ?

**Comment by Romanior** [comment]
As well please use `phone` param not value, with `country` code e.g.
`{{intl-phone-input phone=driver.phone country="AU"}}`

I'm adding support of parsing on init, which I totally forgotten, but please use for now example above ^

**Comment by isAlmogK** [comment]
@Romanior we already have ember-power-select in our project 

"ember-power-select": "1.10.4",
 "ember-power-select-with-create": "^0.6.0", 

And the styles imported 

This is the entire code 

```
<div class="ten wide field">
            <label>Phone</label> 
            {{intl-phone-input phone=driver.phone country="AU"}}
            {{input type="tel" value=driver.phone}}
            {{input-error model=driver attribute="phone"}}
        </div>
```

were also using scss

**Comment by Romanior** [comment]
I'm guessing, I had 'less' only files, published `0.3.1` with scss support and couple of more fixes, including correct copy paste and parsing initial value.
As well verify please that you imported `@import "ember-intl-phone-input";` styles in your app.scss

**Comment by isAlmogK** [comment]
I updated the package and now I'm getting some crazy errors when I run ember server, I removed the package and no errors 

Here are the errors 
```
Stack Trace and Error Report: /var/folders/9p/l8cyx93n5h50qm62m3270m4w0000gp/T/error.dump.5e7e1d982cf9539781481158df0d1dac.log
2018-08-22 12:29 ember[2235] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
Error watching file for changes: EMFILE


Stack Trace and Error Report: /var/folders/9p/l8cyx93n5h50qm62m3270m4w0000gp/T/error.dump.b135626bd84e0b993bcc613b033577e9.log
2018-08-22 12:29 ember[2235] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
Error watching file for changes: EMFILE


Stack Trace and Error Report: /var/folders/9p/l8cyx93n5h50qm62m3270m4w0000gp/T/error.dump.ed09714e34ebb1089b78d5523c08424e.log
2018-08-22 12:29 ember[2235] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
Error watching file for changes: EMFILE


Stack Trace and Error Report: /var/folders/9p/l8cyx93n5h50qm62m3270m4w0000gp/T/error.dump.d16e599153e403e00e17646a09029d4d.log
2018-08-22 12:29 ember[2235] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
Error watching file for changes: EMFILE
```

**Comment by Romanior** [comment]
can you please share `ember -v` output, this looks odd for me.
I prepared twiddle example of usages for you
https://ember-twiddle.com/c38e181747aa387fb4cdfd4c9ad36315?openFiles=twiddle.json%2C

Would it be possible to get a twiddle for your use-case ? thanks

**Comment by isAlmogK** [comment]
Here is the output 

ember-cli: 3.1.4
node: 8.11.3
os: darwin x64

Still getting the issue

**Comment by isAlmogK** [comment]
Here is the output from the log file 

=================================================================================

ENV Summary:

=================================================================================

**Comment by isAlmogK** [comment]
This is also at the start up the error 

018-08-22 21:44 ember[7269] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)

**Comment by isAlmogK** [comment]
It's fixed issue on my machine, permission for watchman was all messed up

**Comment by isAlmogK** [comment]
Not getting the error but still displaying like the screenshot

**Comment by isAlmogK** [comment]
I fixed it by adding the styles sheet directly in my app.

**Comment by isAlmogK** [comment]
Bye, the way thanks for helping me with this issue.
